---

- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  assert:
      that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('(Microsoft Windows Server 2016)')
      success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
      fail_msg: "This role can only be run against Windows Server 2016 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always


- name: Check ansible version
  assert:
      that: ansible_version.full is version_compare(min_ansible_version, '>=')
      msg: You must use Ansible {{ min_ansible_version }} or greater
  tags:
      - always

- name: Language Check (incl. rescue)
  block:
  - name: Check if language is english
    win_shell: AuditPol /get /subcategory:"Credential Validation" /r
    register: isEnglish
    no_log: true

  - name: Set language EN
    set_fact:
      language: "en_US"
    when: '"Machine Name,Policy Target" in isEnglish.stdout'
  rescue:
  - name: Set language DE
    set_fact:
      language: "de_CH"

- name: Set users by language
  set_fact:
    Administrators: Administrators
    RemoteDesktopUsers: Remote Desktop Users
    Guests: Guests
    AuthenticatedUsers: Authenticated Users
    LocalService: Local Service
    NetworkService: Network Service
    Service: Service
    InclusionSetting: "Inclusion Setting"
    sub_CredentialValidation: "Credential Validation"
    sub_KerberosAuthenticationService: "Kerberos Authentication Service"
    sub_ApplicationGroupManagement: "Application Group Management"
    sub_AuditComputerAccountManagement: "Computer Account Management"
    sub_DistributionGroupManagement: "Distribution Group Management"
    sub_OtherAccountManagementEvents: "Other Account Management Events"
    sub_SecurityGroupManagement: "Security Group Management"
    sub_UserAccountManagement: "User Account Management"
    sub_PlugandPlayEvents: "Plug and Play Events"
    sub_ProcessCreation: "Process Creation"
    sub_DirectoryServiceAccess: "Directory Service Access"
    sub_DirectoryServiceChanges: "Directory Service Changes"
    sub_AccountLockout: "Account Lockout"
    sub_GroupMembership: "Group Membership"
    sub_Logoff: "Logoff"
    sub_Logon: "Logon"
    sub_OtherLogonLogoffEvents: "Other Logon/Logoff Events"
    sub_SpecialLogon: "Special Logon"
    sub_DetailedFileShare: "Detailed File Share"
    sub_FileShare: File Share
    sub_OtherObjectAccessEvents: "Other Object Access Events"
    sub_RemovableStorage: "Removable Storage"
    sub_AuditPolicyChange: "Audit Policy Change"
    sub_AuthenticationPolicyChange: "Authentication Policy Change"
    sub_AuthorizationPolicyChange: "Authorization Policy Change"
    sub_MPSSVCRuleLevelPolicyChange: MPSSVC Rule-Level Policy Change
    sub_OtherPolicyChangeEvents: "Other Policy Change Events"
    sub_SensitivePrivilegeUse: "Sensitive Privilege Use"
    sub_IPsecDriver: "IPsec Driver"
    sub_OtherSystemEvents: "Other System Events"
    sub_SecurityStateChange: "Security State Change"
    sub_SecuritySystemExtension: "Security System Extension"
    sub_SystemIntegrity: "System Integrity"
  when: language == "en_US"

- name: Set users by language
  set_fact:
    Administrators: Administratoren
    RemoteDesktopUsers: Remotedesktopbenutzer
    Guests: Gäste
    AuthenticatedUsers: Authentifizierte Benutzer
    LocalService: Lokaler Dienst
    NetworkService: Netzwerkdienst
    Service: Dienst
    InclusionSetting: "Aufnahmeeinstellung"
    sub_CredentialValidation: "Überprüfung der Anmeldeinformationen"
    sub_KerberosAuthenticationService: "Kerberos-Authentifizierungsdienst"
    sub_ApplicationGroupManagement: "Anwendungsgruppenverwaltung"
    sub_AuditComputerAccountManagement: "Computerkontoverwaltung"
    sub_DistributionGroupManagement: "Verteilergruppenverwaltung"
    sub_OtherAccountManagementEvents: "Andere Kontoverwaltungsereignisse"
    sub_SecurityGroupManagement: "Sicherheitsgruppenverwaltung"
    sub_UserAccountManagement: "Benutzerkontenverwaltung"
    sub_PlugandPlayEvents: "Wechselmedien"
    sub_ProcessCreation: "Prozesserstellung"
    sub_DirectoryServiceAccess: "Verzeichnisdienstzugriff"
    sub_DirectoryServiceChanges: "Verzeichnisdienständerungen"
    sub_AccountLockout: "Kontosperrung"
    sub_GroupMembership: "Gruppenmitgliedschaft"
    sub_Logoff: "Abmelden"
    sub_Logon: "Anmelden"
    sub_OtherLogonLogoffEvents: "Andere Anmelde-/Abmeldeereignisse"
    sub_SpecialLogon: "Spezielle Anmeldung"
    sub_DetailedFileShare: "Detaillierte Dateifreigabe"
    sub_FileShare: Dateifreigabe
    sub_OtherObjectAccessEvents: "Andere Objektzugriffsereignisse"
    sub_RemovableStorage: "Wechselmedien"
    sub_AuditPolicyChange: "Richtlinienänderungen überwachen"
    sub_AuthenticationPolicyChange: "Authentifizierungsrichtlinienänderung"
    sub_AuthorizationPolicyChange: "Autorisierungsrichtlinienänderung"
    sub_MPSSVCRuleLevelPolicyChange: MPSSVC-Richtlinienänderung auf Regelebene
    sub_OtherPolicyChangeEvents: "Andere Richtlinienänderungsereignisse"
    sub_SensitivePrivilegeUse: "Sensible Verwendung von Rechten"
    sub_IPsecDriver: "IPSEC-Treiber"
    sub_OtherSystemEvents: "Andere Systemereignisse"
    sub_SecurityStateChange: "Sicherheitsstatusänderung"
    sub_SecuritySystemExtension: "Sicherheitssystemerweiterung"
    sub_SystemIntegrity: "Systemintegrität"
  when: language == "de_CH"

- name: Report Ansible Facts
  ansible.builtin.debug:
    msg: "{{AuthenticatedUsers}}"

- name: Setup for Audit
  import_tasks: setup_audit.yml
  when: setup_audit
  tags:
      - setup_audit

- name: Run Audit
  import_tasks: run_audit.yml
  when: 
      - run_audit
  vars:
      audit_time: pre
  tags:
      - run_audit

- name: Execute the section 1 tasks
  import_tasks: section01.yml
  when: section01_patch | bool
  tags:
      - section01

- name: Execute the section 2 tasks
  import_tasks: section02.yml
  when: section02_patch | bool
  tags:
      - section02

- name: Execute the section 9 tasks
  import_tasks: section09.yml
  when: section09_patch | bool
  tags:
      - section09

- name: Execute the section 17 tasks
  import_tasks: section17.yml
  when: section17_patch | bool
  tags:
      - section17

- name: Execute the section 18 tasks
  import_tasks: section18.yml
  when: section18_patch | bool
  tags:
      - section18

- name: Execute the section 19 tasks
  import_tasks: section19.yml
  when: section19_patch | bool
  tags:
      - section19

- name: Run Audit
  import_tasks: run_audit.yml
  when:
      - run_audit
  vars:
      audit_time: post
  tags:
      - run_audit

- name: Show Audit Summary
  debug:
      msg: "{{ audit_results.split('\n') }}"
  when: 
      - run_audit
  tags:
      - run_audit
